---
title: "Creating new git repo with RStudio"
author: "JML"
date: "January 11, 2017"
output: html_document
---

# Set up a new Project-GitHub link  

For step-by-step instructions see [Stats 545 "Happy Git with R"](http://happygitwithr.com/).
This assumes that you can successfully set up a GitHub connection in RStudio using the instructions.
The following lists the simplest steps which work for me (see [16.1 New Project, GitHub First](http://happygitwithr.com/new-github-first.html)):

  1.  Make a new repo on GitHub  
      *  create with a README.md  
      *  Use the same name for the repo and RStudio Project  
  2.  Start a new Project in RStudio   
      *  New Project > Version Control > Git  
      *  Paste the url in the "repository url"  
  3.  Once the project is created, it should automatically pull in the "README.md" file from GitHub. That's how you know for sure it has connected.  
  4.  Within RStudio make some changes, save, and commit.  
      *  In the Environment panel- click the Git tab to access the commands  
      *  The changes are not permanent unless you Commit.  Make sure to commit at the end of the session.  
  5.  Push to GitHub  
      *  If you're lucky, just "Push" will work  
      *  I can't get the "Push" button to work, so need to use the Git Shell (Git > More > Shell)  
      *  Type `git push -u origin master` at the command line. That should update the GitHub version.
  6.  If you make a change on GitHub, click "Pull"  
      *  Alternatively, just type `git pull -u origin master` in the Git Shell  
  

# A few Git commands

`git push -u origin master` 

`git pull -u origin master`
